In [119]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [121]:
suv_df = pd.read_csv("suv_data.csv")
suv_df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [123]:
suv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [125]:
from sklearn.preprocessing import LabelEncoder

In [127]:
Le = LabelEncoder()

In [75]:
#suv_df['Gender'] = Le.fit_transform(suv_df['Gender'])
#suv_df['Gender'].head()

In [79]:
suv_df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [129]:
#x = suv_df.drop(['User ID', 'Purchased'], axis = 1)
#x=suv_df([['Gender','Age','EstimatedSalary']])
x=suv_df.drop(suv_df[['Gender','Age']], axis=1)
x

      User ID  EstimatedSalary  Purchased
0    15624510            19000          0
1    15810944            20000          0
2    15668575            43000          0
3    15603246            57000          0
4    15804002            76000          0
..        ...              ...        ...
395  15691863            41000          1
396  15706071            23000          1
397  15654296            20000          1
398  15755018            33000          0
399  15594041            36000          1

[400 rows x 3 columns]

In [131]:
y = suv_df['Purchased'].values
x = suv_df['EstimatedSalary'].values
y=y.reshape(len(y),1)
x=x.reshape(len(x),1)
x

array([[ 19000],
       [ 20000],
       [ 43000],
       [ 57000],
       [ 76000],
       [ 58000],
       [ 84000],
       [150000],
       [ 33000],
       [ 65000],
       [ 80000],
       [ 52000],
       [ 86000],
       [ 18000],
       [ 82000],
       [ 80000],
       [ 25000],
       [ 26000],
       [ 28000],
       [ 29000],
       [ 22000],
       [ 49000],
       [ 41000],
       [ 22000],
       [ 23000],
       [ 20000],
       [ 28000],
       [ 30000],
       [ 43000],
       [ 18000],
       [ 74000],
       [137000],
       [ 16000],
       [ 44000],
       [ 90000],
       [ 27000],
       [ 28000],
       [ 49000],
       [ 72000],
       [ 31000],
       [ 17000],
       [ 51000],
       [108000],
       [ 15000],
       [ 84000],
       [ 20000],
       [ 79000],
       [ 54000],
       [135000],
       [ 89000],
       [ 32000],
       [ 44000],
       [ 83000],
       [ 23000],
       [ 58000],
       [ 55000],
       [ 48000],
       [ 79000],
       [ 18000],
       [117000],
       [ 20000],
       [ 87000],
       [ 66000],
       [120000],
       [ 83000],
       [ 58000],
       [ 19000],
       [ 82000],
       [ 63000],
       [ 68000],
       [ 80000],
       [ 27000],
       [ 23000],
       [113000],
       [ 18000],
       [112000],
       [ 52000],
       [ 27000],
       [ 87000],
       [ 17000],
       [ 80000],
       [ 42000],
       [ 49000],
       [ 88000],
       [ 62000],
       [118000],
       [ 55000],
       [ 85000],
       [ 81000],
       [ 50000],
       [ 81000],
       [116000],
       [ 15000],
       [ 28000],
       [ 83000],
       [ 44000],
       [ 25000],
       [123000],
       [ 73000],
       [ 37000],
       [ 88000],
       [ 59000],
       [ 86000],
       [149000],
       [ 21000],
       [ 72000],
       [ 35000],
       [ 89000],
       [ 86000],
       [ 80000],
       [ 71000],
       [ 71000],
       [ 61000],
       [ 55000],
       [ 80000],
       [ 57000],
       [ 75000],
       [ 52000],
       [ 59000],
       [ 59000],
       [ 75000],
       [ 72000],
       [ 75000],
       [ 53000],
       [ 51000],
       [ 61000],
       [ 65000],
       [ 32000],
       [ 17000],
       [ 84000],
       [ 58000],
       [ 31000],
       [ 87000],
       [ 68000],
       [ 55000],
       [ 63000],
       [ 82000],
       [107000],
       [ 59000],
       [ 25000],
       [ 85000],
       [ 68000],
       [ 59000],
       [ 89000],
       [ 25000],
       [ 89000],
       [ 96000],
       [ 30000],
       [ 61000],
       [ 74000],
       [ 15000],
       [ 45000],
       [ 76000],
       [ 50000],
       [ 47000],
       [ 15000],
       [ 59000],
       [ 75000],
       [ 30000],
       [135000],
       [100000],
       [ 90000],
       [ 33000],
       [ 38000],
       [ 69000],
       [ 86000],
       [ 55000],
       [ 71000],
       [148000],
       [ 47000],
       [ 88000],
       [115000],
       [118000],
       [ 43000],
       [ 72000],
       [ 28000],
       [ 47000],
       [ 22000],
       [ 23000],
       [ 34000],
       [ 16000],
       [ 71000],
       [117000],
       [ 43000],
       [ 60000],
       [ 66000],
       [ 82000],
       [ 41000],
       [ 72000],
       [ 32000],
       [ 84000],
       [ 26000],
       [ 43000],
       [ 70000],
       [ 89000],
       [ 43000],
       [ 79000],
       [ 36000],
       [ 80000],
       [ 22000],
       [ 39000],
       [ 74000],
       [134000],
       [ 71000],
       [101000],
       [ 47000],
       [130000],
       [114000],
       [142000],
       [ 22000],
       [ 96000],
       [150000],
       [ 42000],
       [ 58000],
       [ 43000],
       [108000],
       [ 65000],
       [ 78000],
       [ 96000],
       [143000],
       [ 80000],
       [ 91000],
       [144000],
       [102000],
       [ 60000],
       [ 53000],
       [126000],
       [133000],
       [ 72000],
       [ 80000],
       [147000],
       [ 42000],
       [107000],
       [ 86000],
       [112000],
       [ 79000],
       [ 57000],
       [ 80000],
       [ 82000],
       [143000],
       [149000],
       [ 59000],
       [ 88000],
       [104000],
       [ 72000],
       [146000],
       [ 50000],
       [122000],
       [ 52000],
       [ 97000],
       [ 39000],
       [ 52000],
       [134000],
       [146000],
       [ 44000],
       [ 90000],
       [ 72000],
       [ 57000],
       [ 95000],
       [131000],
       [ 77000],
       [144000],
       [125000],
       [ 72000],
       [ 90000],
       [108000],
       [ 75000],
       [ 74000],
       [144000],
       [ 61000],
       [133000],
       [ 76000],
       [ 42000],
       [106000],
       [ 26000],
       [ 74000],
       [ 71000],
       [ 88000],
       [ 38000],
       [ 36000],
       [ 88000],
       [ 61000],
       [ 70000],
       [ 21000],
       [141000],
       [ 93000],
       [ 62000],
       [138000],
       [ 79000],
       [ 78000],
       [134000],
       [ 89000],
       [ 39000],
       [ 77000],
       [ 57000],
       [ 63000],
       [ 73000],
       [112000],
       [ 79000],
       [117000],
       [ 38000],
       [ 74000],
       [137000],
       [ 79000],
       [ 60000],
       [ 54000],
       [134000],
       [113000],
       [125000],
       [ 50000],
       [ 70000],
       [ 96000],
       [ 50000],
       [141000],
       [ 79000],
       [ 75000],
       [104000],
       [ 55000],
       [ 32000],
       [ 60000],
       [138000],
       [ 82000],
       [ 52000],
       [ 30000],
       [131000],
       [ 60000],
       [ 72000],
       [ 75000],
       [118000],
       [107000],
       [ 51000],
       [119000],
       [ 65000],
       [ 65000],
       [ 60000],
       [ 54000],
       [144000],
       [ 79000],
       [ 55000],
       [122000],
       [104000],
       [ 75000],
       [ 65000],
       [ 51000],
       [105000],
       [ 63000],
       [ 72000],
       [108000],
       [ 77000],
       [ 61000],
       [113000],
       [ 75000],
       [ 90000],
       [ 57000],
       [ 99000],
       [ 34000],
       [ 70000],
       [ 72000],
       [ 71000],
       [ 54000],
       [129000],
       [ 34000],
       [ 50000],
       [ 79000],
       [104000],
       [ 29000],
       [ 47000],
       [ 88000],
       [ 71000],
       [ 26000],
       [ 46000],
       [ 83000],
       [ 73000],
       [130000],
       [ 80000],
       [ 32000],
       [ 74000],
       [ 53000],
       [ 87000],
       [ 23000],
       [ 64000],
       [ 33000],
       [139000],
       [ 28000],
       [ 33000],
       [ 60000],
       [ 39000],
       [ 71000],
       [ 34000],
       [ 35000],
       [ 33000],
       [ 23000],
       [ 45000],
       [ 42000],
       [ 59000],
       [ 41000],
       [ 23000],
       [ 20000],
       [ 33000],
       [ 36000]], dtype=int64)

In [133]:
from sklearn.model_selection import train_test_split

In [135]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=10)

In [137]:
from sklearn.linear_model import LogisticRegression

In [139]:
log = LogisticRegression()

In [141]:
# Train the model
log.fit(x_train, y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [143]:
y_pred = log.predict(x_test)
print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 1 1 0]

In [145]:
log.score(x_test, y_test)

0.8083333333333333

In [147]:
from sklearn import metrics
# Accuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')
# Precision
precision = metrics.precision_score(y_test, y_pred, zero_division=0) # The z
print(f'Precision: {precision}') # 0, means that out of all the positive pre
# Recall
recall = metrics.recall_score(y_test, y_pred)
print(f'Recall: {recall}') # 0, means that out of all the positive predictio
# F1 Score
f1_score = metrics.f1_score(y_test, y_pred)
print(f'F1 Score: {f1_score}') # F1 score is the harmonic mean of precision 
# AUC-ROC
auc_roc = metrics.roc_auc_score(y_test, y_pred)
print(f'AUC-ROC: {auc_roc}')
# Confusion Matrix
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix: \n{confusion_matrix}')
print()
# Mean Absolute Error (MAE)
mae = metrics.mean_absolute_error(y_test, y_pred)
print(f'MAE: {mae}') # 0.4167, means that on average, your model’s predictio
# Root Mean Square Error (RMSE)
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print(f'RMSE: {rmse}') # 0.6455, means that on average, the square root of t
# R2 Score
r2 = metrics.r2_score(y_test, y_pred) # R2 score of 1 indicates that the mod
print(f'R2 Score: {r2}') # A negative R2 score indicates that your model is 
# Adjusted R2 Score
n = len(y_test) # Number of observations
k = 1 # Number of predictors
adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - k - 1)
print(f'Adjusted R2 Score: {adjusted_r2}') # A negative R2 score indicates t

Accuracy: 0.8083333333333333
Precision: 0.85
Recall: 0.4594594594594595
F1 Score: 0.5964912280701754
AUC-ROC: 0.7116574405731032
Confusion Matrix:
[[80  3]
 [20 17]]

MAE: 0.19166666666666668
RMSE: 0.43779751788545657
R2 Score: 0.10126994464343841
Adjusted R2 Score: 0.09365358824211156

In [104]:
!python --version

Python 3.12.4